language: scala
scala: 2.11.12

addons:
  apt:
    packages:
    - libgtest-dev
    - p7zip-full
    - yasm

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt
  - $PWD/_git
  - $PWD/_install

matrix:
  include:
  # Test builds first, since they don't upload things.
  - env: GOAL=test TARGET=host
#    stage: Test
  - env: GOAL=test TARGET=host
    language: generic
    os: osx
    install: brew install sbt
  # Production builds after test builds so only tested artifacts are uploaded.
#  - env: GOAL=release TARGET=host
#    stage: Release
  - env: GOAL=release TARGET=aarch64-linux-android
  - env: GOAL=release TARGET=arm-linux-androideabi
  - env: GOAL=release TARGET=i686-linux-android
  - env: GOAL=release TARGET=x86_64-linux-android
  fast_finish: true

install:
- test -f _install/host/protobuf.stamp || scripts/build-host -j$(nproc || sysctl -n hw.ncpu) $PWD/_install/host/protobuf.stamp

script:
- scripts/build-$TARGET -j$(nproc || sysctl -n hw.ncpu) $GOAL

after_success:
- if [ "$GOAL" = "test" ]; then sbt coveralls; fi

branches:
  only:
  - master
